### ISSUE TITLE
[Query] What is the purpose of this repository?

### ISSUE THREAD

**Issue by jaju** [tsachev/reactor-core-clojure#1]
Hi @tsachev!
Thanks for sharing your work - very instructive/educational code to study.

Did you create it with some intention, or only as a playground for exploring async and interop from clojure <-> jvm/js?

Do you plan to update it - both with changes in the reactive libraries as well documentation to guide how it can be used?

Thanks,
jaju

**Comment by tsachev** [comment]
Hi @jaju 

My intention was to make a clojure(script) wrapper around [reactor-core](https://github.com/reactor/reactor-core) on the jvm and [reactor-core-js](https://github.com/reactor/reactor-core-js) for browser/node. I was even a contributor at reactor-core-js for some time - but this project seems dead now.
The real reason was that I worked on a timeseries datastore which was accessible via [rsocket](https://github.com/rsocket).
And I wanted to be able to write applications in clojure to process the data using flux/mono. And I want these applications to run on jvm, node and browser.

As you can see I have no commits for the past 3 years. It would be great to refresh this project and align it with latest reactor versions. I hope I will not have to drop js support to move forward.

Thanks for reminding me about this code.

**Comment by jaju** [comment]
Thanks, @tsachev - I have been going through your code, and am greatly enjoying reading your code.
In my hope to get more familiar, I started to play with the build-tooling too, and have the tests now running (and passing) using clojure-cli and shadow-cljs, and with _updated_ versions of all dependencies. But JS compilation throws up some warnings, and I am not much good with Javascript.

I'll be very happy to follow your updates and find ways to use it - I come across reactor from the Java side in my regular work and was keen to explore integrating Clojure into my codebase, when I came across your repository.
The core types in the reactor library have been pretty stable, so the code works just fine with JVM reactor-core 3.4.9.

I'll be happy to help in any way I can!
